### ISSUE TITLE
[Bug] ESM Support: 最新版本的electron-vite-vue里，使用esm模块报错，require() of ES Module ... not supported.

### ISSUE THREAD

**Issue by spianmo** [caoxiemeihao/electron-vite-boilerplate#25]
#### 在最新的electron-vite-vue里，使用ESM模块报错。我已经添加了vite-plugin-esmodule依赖，版本号为1.3.2；并在dependencies中添加了如下ESM模块依赖
```
  "dependencies": {
    "execa": "^6.1.0",
    "file-type": "^17.1.1",
    "move-file": "^3.0.0",
    "node-fetch": "^3.2.4"
  },
```
#### 并在vite.config.ts中添加了如下代码块

```
    esmodule([
      'execa',
      'node-fetch',
      'file-type',
      'move-file',
    ]),
```
#### 编译时提示esm编译成功
![image](https://user-images.githubusercontent.com/18194268/177902251-17415c37-ddb5-4171-b575-c6971e0ee6dc.png)

#### 但是在运行时提示require() of ES Module ... not supported.
```
[⚡️ Vite] Error [ERR_REQUIRE_ESM]: require() of ES Module E:\FrontendProjects\MeiTuanAdmin\node_modules\execa\index.js from E:\FrontendProjects\MeiTuanAdmin\dist\electron\main\index.js not supported.
[⚡️ Vite] Instead change the require of E:\FrontendProjects\MeiTuanAdmin\node_modules\execa\index.js in E:\FrontendProjects\MeiTuanAdmin\dist\electron\main\index.js to a dynamic import() which is available in all CommonJS modulees.
[⚡️ Vite]     at c._load (node:electron/js2c/asar_bundle:5:13343)
[⚡️ Vite]     at Module.<anonymous> (E:\FrontendProjects\MeiTuanAdmin\dist\electron\main\index.js:8:13)
[⚡️ Vite]     at c._load (node:electron/js2c/asar_bundle:5:13343)
[⚡️ Vite]     at loadApplicationPackage (E:\FrontendProjects\MeiTuanAdmin\node_modules\electron\dist\resources\default_app.asar\main.js:110:16)
[⚡️ Vite]     at Object.<anonymous> (E:\FrontendProjects\MeiTuanAdmin\node_modules\electron\dist\resources\default_app.asar\main.js:222:9)
[⚡️ Vite]     at c._load (node:electron/js2c/asar_bundle:5:13343)
[⚡️ Vite]     at Object.<anonymous> (node:electron/js2c/browser_init:185:3104)
[⚡️ Vite]     at ./lib/browser/init.ts (node:electron/js2c/browser_init:185:3308)
[⚡️ Vite]     at __webpack_require__ (node:electron/js2c/browser_init:1:128)
[⚡️ Vite]     at node:electron/js2c/browser_init:1:1200
[⚡️ Vite]     at node:electron/js2c/browser_init:1:1267
[⚡️ Vite]     at c._load (node:electron/js2c/asar_bundle:5:13343)
```
#### 运行报错截图
![image](https://user-images.githubusercontent.com/18194268/177902136-1fbba289-6058-4fc6-a1bd-11a3135f1251.png)

**Comment by spianmo** [comment]
#### 在主进程中，我的execa使用方式
```
import {execa, Options} from 'execa'

async function _execa(file: string,
                      arguments?: readonly string[],
                      options?: Options<null>) {
    const {stdout} = await execa(file, arguments, options)

    console.log(stdout)
}
```

**Comment by caoxiemeihao** [comment]
你确定你的项目在渲染进程开启了 Node.js 能力？
```ts
    webPreferences: {
      contextIsolation: false,
      nodeIntegration: true,
    },
```

**Comment by spianmo** [comment]
> 你确定你再渲染进程开启了 Node.js 能力？

我是在主进程使用的execa，并不是在渲染进程，渲染进程ipc调用主进程里的execa

**Comment by spianmo** [comment]
> ```ts
> nodeIntegration
> ```

![image](https://user-images.githubusercontent.com/18194268/177910106-4ea57c96-ca27-461d-b80a-ac1736e7bb3d.png)

**Comment by spianmo** [comment]
> 你确定你的项目在渲染进程开启了 Node.js 能力？
> 
> ```ts
>     webPreferences: {
>       contextIsolation: false,
>       nodeIntegration: true,
>     },
> ```

![image](https://user-images.githubusercontent.com/18194268/177910182-36c821c2-e4e3-425a-82f9-3dc5b1d3897b.png)

**Comment by caoxiemeihao** [comment]
> 我是在主进程使用的execa，并不是在渲染进程，渲染进程ipc调用主进程里的execa

主要进程使用 execa 不用装 `vite-plugin-esmodule` 这块设计失误。。。
我更新个版本，你稍微当我一小会儿。。。

**Comment by caoxiemeihao** [comment]
1. `packages/main/vite.config.ts`
```diff
    rollupOptions: {
      external: [
        'electron',
        ...builtinModules,
+       ...builtinModules.map(e => `node:${e}`),
        ...Object.keys(pkg.dependencies || {}),
      ],
    },
```
2. 把 `execa` 放到 `devDependencies` 

这么两步就能用了，你先这么用着；我有事今天不搞了，明天再说。。。

**Comment by spianmo** [comment]
> 1. `packages/main/vite.config.ts`
> 
> ```diff
>     rollupOptions: {
>       external: [
>         'electron',
>         ...builtinModules,
> +       ...builtinModules.map(e => `node:${e}`),
>         ...Object.keys(pkg.dependencies || {}),
>       ],
>     },
> ```
> 
> 2. 把 `execa` 放到 `devDependencies`
> 
> 这么两步就能用了，你先这么用着；我有事今天不搞了，明天再说。。。

感谢！

**Comment by caoxiemeihao** [comment]
代码已经更新 :)
