### ISSUE TITLE
[Help] The task `start.debug.script.mjs`cannot be tracked. Make sure to have a problem matcher defined.

### ISSUE THREAD

**Issue by yi-Xu-0100** [caoxiemeihao/electron-vite-boilerplate#27]
#### Describe the problem you confuse

这个仓库我看到有 script ，所以我尝试用这个在 vscode 中 debug，但是提示 `The task 'start.debug.script.mjs' cannot be tracked. Make sure to have a problem matcher defined.`

但是成功显示了 electron 界面如图所示：

![图片](https://user-images.githubusercontent.com/25523606/180229753-1b8e45f1-0d3a-481d-a1f8-e9d72c06d5da.png)

看起来和 readme 的图片一致。

![图片](https://user-images.githubusercontent.com/25523606/180230698-03e5e39c-64a3-4968-a304-4118bc1f4e9f.png)

这里我选择了 `Debug Anyway`，会让 electron 窗口再出现相同的一个。

我不确定这是否正常，应该默认选择什么选项吗？或者应该设置什么去解决这个弹窗吗？

**Comment by caoxiemeihao** [comment]
这个 Debug 有点小问题，明天看看修复下。

**Comment by caoxiemeihao** [comment]
The Debug feature has been fixed. https://github.com/electron-vite/electron-vite-boilerplate/commit/5e51071f92a3719a245038cfd5d5ec7280e9897c

But `The task start.debug.script.mjscannot be tracked. ` still needs to wait for the solution.

**Comment by caoxiemeihao** [comment]
@yi-Xu-0100 Hey bro! 👋
If you like the organization `electron-vite` and use communicate in Issues in English. I hope you can join the organization. 😄

**Comment by yi-Xu-0100** [comment]
@caoxiemeihao Thank you very much for your invitation, it will be a great pleasure for me to join the organization. But I must tell you that I am really newer for both Vue and electron. Recently, I will try to learn them and would give help if needed. 😁
