### ISSUE TITLE
[Help] Cannot write file 'xxxx/electron-vite-boilerplate/dist/main/index.cjs' because it would overwrite input file.

### ISSUE THREAD

**Issue by yi-Xu-0100** [caoxiemeihao/electron-vite-boilerplate#28]
#### Describe the problem you confuse

我使用 `VSCode` 的时候，在 `tsconfig.json` 文件中会有提示错误。

``` log
Cannot write file 'xxxx/electron-vite-boilerplate/dist/main/index.cjs' because it would overwrite input file. #ts [Ln 1, Col 1]
```

我尝试查找了一下原因，找到了这个说法： [当我使用 `javascript` 文件时，为什么我会得到 `error ts5055 cannot write file xxx js because it would overwrite input file` 错误？](https://jkchao.github.io/typescript-book-chinese/faqs/tsconfig-behavior.html#当我使用-javascript-文件时，为什么我会得到-error-ts5055-cannot-write-file-xxx-js-because-it-would-overwrite-input-file-错误？)

> 对于 `TypeScript` 文件来说，在默认情况下，编译器将在同一目录中生成与 `JavaScript` 相同文件名的文件。因为 `TypeScript` 文件与编译后的文件总是拥有不同的后缀，这么做是安全的。然而，如果你设置 `allowJs` 编译选项为 `true` 和没有设置任何的编译输出属性（`outFile` 和 `outDir`），编译器将会尝试使用相同的规则来编译文件，这将导致发出的 `JavaScript` 文件与源文件具有相同的文件名。为了避免意外覆盖源文件，编译器将会发出此警告，并跳过编写输出文件。
> 
> 有多种方法可以解决此问题，但所有这些方法都涉及配置编译器选项，因此建议你在项目根目录中的 `tsconfig.json` 文件来启用此功能。如果你不想编译 `JavaScript` 文件，你只需要将 `allowJs` 选项设置为 `false`；如果你确实想要包含和编译这些 `JavaScript` 文件，你应该设置 `outDir` 或者 `outFile` 选项，定向到其他位置，这样他们就不会与源文件冲突。如果你仅仅是想包含这些 `JavaScript` 文件，但是不需要编译，设置 `noEmit` 选项为 `true` 可以跳过编译检查。

可以看出，样版中的 `tsconfig.json` 将 `allowJs` 选项设置为 `true` ，但是没有设置 `outDir` 或者 `outFile` 选项，造成了这个报错，但是我不太了解这里应该怎么指定不同的编译路径以避免这个问题。

**Comment by caoxiemeihao** [comment]
可能模板没必要 allowJs 可以提个 PR 删掉。其次 outDir 也用不到，因为是 Vite 控制的。
