### ISSUE TITLE
求助打包时svg-sprite-loader问题

### ISSUE THREAD

**Issue by jenifly** [caoxiemeihao/electron-vite-boilerplate#3]
使用了svg-sprite-loader在webpack打包，svg图标没了....
配置如下
{
  test: /\.svg$/,
  loader: "svg-sprite-loader",
  // include: [resolveRoot("src/render/assets/svg")],
  options: {
    symbolId: "icon-[name]",
  },
},

**Comment by caoxiemeihao** [comment]
```diff
- test: /.svg$/,
+ test: /\.svg$/,
```
