### ISSUE TITLE
systemPreferences support

### ISSUE THREAD

**Issue by jbaubree** [caoxiemeihao/electron-vite-boilerplate#4]
Hi, i'm new in electron, is there any way to get the import { systemPreferences } from 'electron' and use this function in a vue component?

**Comment by caoxiemeihao** [comment]
![image](https://user-images.githubusercontent.com/26263658/150663265-c8967fda-cb74-4acf-af87-bf04562c253d.png)  

`systemPreferences` can only used in `Main-Process`，"vue component" run at `Renderer-Process`;  

You can through `ipcRenderer` to use it.
