### ISSUE TITLE
serialport版本已经是10.3.0,已经自带类型且不支持默认导出,请问vite-plugin-electron-renderer中应该怎么写,

### ISSUE THREAD

**Issue by wgcairui** [caoxiemeihao/electron-vite-boilerplate#7]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/12164036/155825493-e2421683-b095-43d3-892b-fd8b11bd03c8.png">

serialport更改
https://serialport.io/docs/guide-upgrade

**Comment by wgcairui** [comment]
已经解决了,虽然我也看不懂为什么这样可以???
<img width="424" alt="image" src="https://user-images.githubusercontent.com/12164036/155827304-3a567f41-72e3-45c4-8546-2467858a9ed7.png">
<img width="450" alt="image" src="https://user-images.githubusercontent.com/12164036/155827345-81f7aeb3-96cb-4712-b148-e176efcf821e.png">

**Comment by caoxiemeihao** [comment]
`serialport` 导出有变化，所以你要及时更新你的写法
